User.create(user_name: "Jack0Laturn", first_name:"Jack", email:"jack@gmail.com", password:"12345")
User.create(user_name: "Sayid", email:"Sayid@gmail.com", password:"12345")
User.create(user_name: "Ben", email:"Ben@gmail.com", password:"12345")
User.create(user_name: "Kate", email:"Kate@gmail.com", password:"12345")
User.create(user_name: "Claire", email:"Claire@gmail.com", password:"12345")
User.create(user_name: "John", email:"John@gmail.com", password:"12345")